pub mod pages;
pub mod user_controller;
pub mod docs_controller;
pub mod inertia_controller;

pub use pages::*;
pub use user_controller::*;
pub use docs_controller::*;
pub use inertia_controller::*;
pub mod post_controller;
pub use post_controller::*;
pub mod posts_controller;
pub use posts_controller::*;
pub mod comment_controller;
pub use comment_controller::*;
pub mod category_controller;
pub use category_controller::*;
pub mod product_controller;
pub use product_controller::*;
