[tasks.kit]
workspace = false
command = "cargo"
args = ["install", "--path", ".", "--force"]

[tasks.install-watch]
command = "cargo"
args = ["install", "cargo-watch"]

[tasks.watch-templates]
dependencies = ["install-watch"]
command = "cargo"
args = ["watch", "-w", "templates", "-w", "src", "-x", "build"]

[tasks.watch-server]
dependencies = ["install-watch"]
command = "cargo"
args = ["watch", "-w", "templates", "-w", "src", "-x", "run"]

[tasks.watch-assets]
command = "npm"
args = ["run", "dev"]

[tasks.dev]
workspace = false
run_task = { name = ["watch-assets", "watch-server"], parallel = true } 

[tasks.run-migrations]
command = "cargo"
args = ["kit", "migrate"]

[tasks.run-migrations-fresh]
command = "cargo"
args = ["kit", "migrate:fresh"]

[tasks.migrate]
workspace = false
run_task = { name = ["kit", "run-migrations"], parallel = false }

[tasks.migrate-fresh]
workspace = false
run_task = { name = ["kit", "run-migrations-fresh"], parallel = false }

[tasks.script]
workspace = false
command = "cargo"
args = ["run", "--package", "rustavel-scripts", "--bin", "${@}"]