[tasks.kit]
command = "cargo"
args = ["install", "--path", ".", "--force"]

[tasks.install-watch]
command = "cargo"
args = ["install", "cargo-watch"]

[tasks.watch-templates]
dependencies = ["install-watch"]
command = "cargo"
args = ["watch", "-w", "templates", "-w", "src", "-x", "build"]

[tasks.watch-server]
dependencies = ["install-watch"]
command = "cargo"
args = ["watch", "-w", "templates", "-w", "src", "-x", "run"]

[tasks.watch-assets]
command = "npm"
args = ["run", "dev"]

[tasks.dev]
run_task = { name = ["watch-assets", "watch-server"], parallel = true } 