[template]
cargo_generate_version = ">=0.10.0"

[placeholders.description]
type = "string"
prompt = "Project description"
default = "A web application built with Ruskit"

[placeholders.authors]
type = "string"
prompt = "Author name"
default = "Your Name <your.email@example.com>" 