[tasks.install-watch]
install_crate = { crate_name = "cargo-watch", binary = "cargo-watch", test_arg = "--help" }

[tasks.dev]
dependencies = ["install-watch"]
command = "cargo"
args = ["watch", "-w", "templates", "-w", "src", "-x", "run"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.lint]
command = "cargo"
args = ["clippy"]

[tasks.check]
dependencies = ["format", "lint"]
command = "cargo"
args = ["check"] 