// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AboutPageProps { tech_stack: Array<string>, why_choose_us: Array<string>, test: string | null, }
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostDto } from "./PostDto";

export interface PostListProps { posts: Array<PostDto>, }
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PostDto { id: number, title: string, content: string, slug: string, created_at: string, updated_at: string, }