// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AboutPageProps {
  title: string;
  description: string;
  tech_stack: Array<string>;
}
